[package]
name = "shit_jit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bad64 = "0.6.0"
dynasmrt = "1.2.3"
iced-x86 = "1.17.0"
memmap = "0.7.0"
